FORMAT: 1A
HOST: http://tapnwin.ludopia.net/api

# Tap&Win API

Introduction goes here

# Group General

:[Session](general/user/session.md)

:[Users](general/user/users.md)

:[User](general/user/user.md)

:[Companies](general/company/companies.md)

:[Company](general/company/company.md)

:[Campaigns](general/campaign/campaigns.md)

:[Campaign](general/campaign/campaign.md)

# Group Diseña y gana

:[Categories](general/category/categories.md)

:[Category](general/category/category.md)

:[Models](general/model/models.md)

:[Model](general/model/model.md)

# Group Voz de la gente

# Group Match 3

# Group Dueño de tiendas
