FORMAT: 1A
HOST: http://tapnwin.ludopia.net/api

# Tap&Win API

Introduction goes here

# Group General

:[Session](general/user/session.md)

:[Users](general/user/users.md)

# Group Diseña y gana

# Group Voz de la gente

# Group Match 3

# Group Dueño de tiendas
