FORMAT: 1A
HOST: http://tapnwin.ludopia.net/api

# Tap&Win API

Introduction goes here

# Group General

:[Session](general/user/session.md)

:[Users](general/user/users.md)

:[User](general/user/user.md)

:[Companies](general/company/companies.md)

:[Company](general/company/company.md)

:[Campaigns](general/campaign/campaigns.md)

:[Campaign](general/campaign/campaign.md)

:[Games](general/game/games.md)

:[Game](general/game/game.md)

# Group Diseña y gana

:[Categories](general/category/categories.md)

:[Category](general/category/category.md)

:[Models](general/model/models.md)

:[Model](general/model/model.md)

:[Designs](general/design/designs.md)

:[Design](general/design/design.md)

:[Missions](general/mission/missions.md)

:[Mission](general/mission/mission.md)

:[Statuses](general/status/statuses.md)

:[Status](general/status/status.md)

:[Stickers](general/sticker/stickers.md)

:[Sticker](general/sticker/sticker.md)

:[Votes](general/vote/votes.md)

:[Vote](general/vote/vote.md)

# Group Voz de la gente

# Group Match 3

# Group Dueño de tiendas
