FORMAT: 1A
HOST: http://tapnwin.ludopia.net/api/v1

# Tap&Win API

Introduction goes here

# Group General

:[Session](common/user/session.md)

:[Users](common/user/users.md)

:[User](common/user/user.md)

:[Administrators](common/administrator/administrators.md)

:[Administrator](common/administrator/administrator.md)

:[Players](common/player/players.md)

:[Player](common/player/player.md)

:[Companies](common/company/companies.md)

:[Company](common/company/company.md)

:[Campaigns](common/campaign/campaigns.md)

:[Campaign](common/campaign/campaign.md)

:[Missions](common/mission/missions.md)

:[Mission](common/mission/mission.md)

:[MissionStatuses](common/status/statuses.md)

:[MissionStatus](common/status/status.md)

:[CampaignStatus](common/campaignStatus/campaignStatus.md)

:[Time](common/misc/time.md)

# Group Diseña y gana

:[Categories](dyg/category/categories.md)

:[Category](dyg/category/category.md)

:[Models](dyg/model/models.md)

:[Model](dyg/model/model.md)

:[Designs](dyg/design/designs.md)

:[Design](dyg/design/design.md)

:[Stickers](dyg/sticker/stickers.md)

:[Sticker](dyg/sticker/sticker.md)

:[items](dyg/item/items.md)

:[item](dyg/item/item.md)

:[Votes](dyg/vote/votes.md)

:[Vote](dyg/vote/vote.md)

# Group Voz de la gente

:[Answers](vdlg/answer/answers.md)

:[Answer](vdlg/answer/answer.md)

# Group Match 3

# Group Dueño de tiendas
