FORMAT: 1A
HOST: http://tapnwin.ludopia.net/api/v1

# Tap&Win API

Introduction goes here

# Group General

:[Session](common/user/session.md)

:[Users](common/user/users.md)

:[User](common/user/user.md)

:[Companies](common/company/companies.md)

:[Company](common/company/company.md)

:[Campaigns](common/campaign/campaigns.md)

:[Campaign](common/campaign/campaign.md)

:[Games](common/game/games.md)

:[Game](common/game/game.md)

:[Missions](common/mission/missions.md)

:[Mission](common/mission/mission.md)

# Group Diseña y gana

:[Categories](design/category/categories.md)

:[Category](design/category/category.md)

:[Models](design/model/models.md)

:[Model](design/model/model.md)

:[Designs](design/design/designs.md)

:[Design](design/design/design.md)

:[Statuses](design/status/statuses.md)

:[Status](design/status/status.md)

:[Stickers](design/sticker/stickers.md)

:[Sticker](design/sticker/sticker.md)

:[Votes](design/vote/votes.md)

:[Vote](design/vote/vote.md)

# Group Voz de la gente

# Group Match 3

# Group Dueño de tiendas
