FORMAT: 1A
HOST: http://tapnwin.ludopia.net/api/v1

# Tap&Win API

Introduction goes here

# Group General

:[Session](common/user/session.md)

:[Users](common/user/users.md)

:[User](common/user/user.md)

:[Administrators](common/administrator/administrators.md)

:[Administrator](common/administrator/administrator.md)

:[Players](common/player/players.md)

:[Player](common/player/player.md)

:[Companies](common/company/companies.md)

:[Company](common/company/company.md)

:[Campaigns](common/campaign/campaigns.md)

:[Campaign](common/campaign/campaign.md)

:[Missions](common/mission/missions.md)

:[Mission](common/mission/mission.md)

:[MissionStatuses](common/status/statuses.md)

:[MissionStatus](common/status/status.md)

:[CampaignStatus](common/campaignStatus/campaignStatus.md)

:[Time](common/misc/time.md)

# Group Diseña y gana

:[Categories](design/category/categories.md)

:[Category](design/category/category.md)

:[Models](design/model/models.md)

:[Model](design/model/model.md)

:[Designs](design/design/designs.md)

:[Design](design/design/design.md)

:[Stickers](design/sticker/stickers.md)

:[Sticker](design/sticker/sticker.md)

:[items](design/item/items.md)

:[item](design/item/item.md)

:[Votes](design/vote/votes.md)

:[Vote](design/vote/vote.md)

# Group Voz de la gente

# Group Match 3

# Group Dueño de tiendas
